"""
Trains gradient boosting regressors to predict dynamic lift-test outcomes
(per-joint sag_deg, max_applied_torque_nm) from design parameters, using
the dataset generated by generate_dataset.py.

One model per target (not one multi-output model) - simpler to evaluate
each target's learnability independently, and to spot-check predictions
per-metric later.

Honest evaluation: held-out test split, real R^2/MAE reported - not just
training fit, which would be misleadingly optimistic.
"""

import joblib
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

from src.ml.generate_dataset import PARAM_RANGES

FEATURE_COLUMNS = list(PARAM_RANGES.keys())
TARGET_COLUMNS = [
    "shoulder_sag_deg",
    "shoulder_max_applied_torque_nm",
    "elbow_sag_deg",
    "elbow_max_applied_torque_nm",
]


def train_all_models(dataset_path: str = "data/lift_test_dataset.csv", seed: int = 0):
    df = pd.read_csv(dataset_path)
    X = df[FEATURE_COLUMNS]

    models = {}
    metrics = {}

    for target in TARGET_COLUMNS:
        y = df[target]
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=seed
        )

        model = GradientBoostingRegressor(
            n_estimators=200, max_depth=3, learning_rate=0.05, random_state=seed
        )
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        r2 = r2_score(y_test, y_pred)
        mae = mean_absolute_error(y_test, y_pred)

        models[target] = model
        metrics[target] = {"r2": r2, "mae": mae}

        print(f"{target}: R^2={r2:.4f}  MAE={mae:.4f}")

    return models, metrics


if __name__ == "__main__":
    models, metrics = train_all_models()

    import os
    os.makedirs("data/models", exist_ok=True)
    for target, model in models.items():
        joblib.dump(model, f"data/models/{target}_model.joblib")

    print("\nModels saved to data/models/")
